name: math_fast
description: An exciting match game.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  bloc: ^6.1.1
  cupertino_icons: ^1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^6.1.1
  http: ^0.12.0+1
  provider: ^4.3.2+2
  rxdart: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Comfortaa
      fonts:
        - asset: fonts/Comfortaa/Comfortaa-Bold.ttf
          weight: 700
        - asset: fonts/Comfortaa/Comfortaa-SemiBold.ttf
          weight: 600
        - asset: fonts/Comfortaa/Comfortaa-Medium.ttf
          weight: 500
        - asset: fonts/Comfortaa/Comfortaa-Regular.ttf
          weight: 400
        - asset: fonts/Comfortaa/Comfortaa-light.ttf
          weight: 300
