name: Test

on:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: macos-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.22.4'

      - name: Install Dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test --coverage

      - name: Report Coverage
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./coverage/lcov.info
